# Generated by Django 5.0.1 on 2024-01-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0002_tag_alter_post_options_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artist',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=800, null=True),
        ),
    ]
